import json
# Assuming an LLM client interface (e.g., OpenAI or custom HuggingFace pipeline)
# from your_llm_provider import LLMClient

class AttributionEngine:
    """
    Generates institutional-grade post-trade attribution reports by aggregating
    data from the CBM, Symbolic Regression, GNN, and RL Execution modules.
    """
    def __init__(self, llm_client):
        self.llm = llm_client

        # The rigid prompt template forces the LLM to adhere to a strict, professional format
        self.prompt_template = """
        You are a Quantitative Portfolio Manager generating a post-trade attribution report.
        Based on the following trade metadata generated by Project CausalFlow, write a concise,
        professional Markdown report detailing the 'Why' and 'How' of the trade execution.

        --- TRADE METADATA ---
        Asset: {asset}
        Direction: {direction}
        Size: {size}

        1. LAYER 2 (CBM Concepts):
        The neural network detected these primary market drivers: {cbm_concepts}

        2. LAYER 3 (Causal Alpha):
        The LLM-Symbolic Regression engine utilized this formula: {alpha_formula}
        Causal Directionality Test P-Value: {causal_p_value}

        3. LAYER 3 (GNN Attention):
        The Knowledge Graph focused on these nodes: {gnn_attention}

        4. LAYER 4 (Execution & Frictions):
        RL Agent Route: {execution_route}
        Estimated Slippage vs Ideal Alpha: {slippage} bps
        Staleness Gap: {latency_ms} ms

        --- REQUIRED REPORT STRUCTURE ---
        ## Trade Summary
        ## Factor & Causal Attribution (Explain the CBM and Alpha formula logic)
        ## Structural Network Drivers (Explain the GNN graph logic)
        ## Execution Quality & Sim-to-Real Frictions (Analyze the RL agent's performance)

        Do not invent data. Rely strictly on the metadata provided.
        """

    def generate_report(self, trade_data: dict) -> str:
        """
        Ingests the trade dictionary and outputs the Markdown report.
        """
        # Format the prompt with the extracted trade telemetry
        formatted_prompt = self.prompt_template.format(
            asset=trade_data.get("asset", "Unknown"),
            direction=trade_data.get("direction", "Unknown"),
            size=trade_data.get("size", 0),
            cbm_concepts=json.dumps(trade_data.get("cbm_concepts", {})),
            alpha_formula=trade_data.get("alpha_formula", "N/A"),
            causal_p_value=trade_data.get("causal_p_value", "N/A"),
            gnn_attention=json.dumps(trade_data.get("gnn_attention", {})),
            execution_route=trade_data.get("execution_route", "N/A"),
            slippage=trade_data.get("slippage", 0.0),
            latency_ms=trade_data.get("latency_ms", 0)
        )

        # Generate the report via LLM
        if hasattr(self.llm, "generate_prompt") and callable(self.llm.generate_prompt):
            response = self.llm.generate_prompt(formatted_prompt)
        elif hasattr(self.llm, "chat") and callable(self.llm.chat):
            response = self.llm.chat(formatted_prompt)
        else:
            response = f"Fallback LLM Response generated for {trade_data.get('asset')} based on prompt."

        return response

# Example Usage:
# engine = AttributionEngine(llm_client=my_llm)
# trade_telemetry = {
#     "asset": "AAPL", "direction": "SELL", "size": 5000,
#     "cbm_concepts": {"Micro-Volatility": 0.89, "Retail_Order_Imbalance": 0.72},
#     "alpha_formula": "Rank(Ts_StdDev(Volume, 10) / Liquidity_Premium)",
#     "causal_p_value": 0.012,
#     "gnn_attention": {"TSMC_Supply_Chain_Anomaly": 0.65},
#     "execution_route": "Passive-Aggressive Split (70/30)",
#     "slippage": 1.2, "latency_ms": 45
# }
# report = engine.generate_report(trade_telemetry)